services:
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: seminar_db
      MYSQL_USER: seminar_user
      MYSQL_PASSWORD: seminar_password
    ports:
      - "3307:3306"
    volumes:
      - seminar_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - my_new_network

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: seminar-api-db-1
      DB_USER: seminar_user
      DB_PASSWORD: seminar_password
      DB_NAME: seminar_db
    depends_on:
      - db
    networks:
      my_new_network:
      traefik_net:
        aliases:
          - seminar-api

volumes:
  seminar_data:

networks:
  my_new_network:
  traefik_net:
    external: true
    name: docker-compose_exam1-net
